layout_spectrum: 0.2682701
typography_spectrum: 0.4139785
color:
  saturation: 0.2706093
  brandStrength: 0.2279031
  lightness: 0.7580645
  rhythmicContrast: 0.3100359
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Jess Traviglia
